scenario:
  high_level_category: srh
  subcategory: contraception
  tone: shy                                                             # options: shy, knowledge_barrier, confused, none_neutral_just_curious, fear_shame_stigma, anxiety_overwhelm, positive_health_seeking
  barrier: knowledge_barrier
  gender: female
  age: 18
  edge_case: null
  free_form: "The user is in a rural area with no clinic access"

settings:
  n_convos: 3
  n_turns: [3,4,5]    # integer (same for all) OR a list matching n_convos, e.g. [3, 4, 5]
  mid_convo_topic_change:
    topic: "random"   # null (no switch), "random", or a specific topic e.g. "stis"
    at_turn: null     # null = random turn, or a specific turn number e.g. 2

distributions:
  high_level_category:
    srh: 0.7483
    mwb: 0.2469
    both: 0.0048

  subcategory:
    puberty_and_body_changes: 0.1299
    menstruation_and_cycle_issues: 0.0577
    pregnancy: 0.1607
    abortion: 0.0061
    contraception: 0.0428
    stis: 0.0455
    hiv_aids: 0.0196
    intimate_relationships_and_consent: 0.5301
    srh_services: 0.0076

  tone:
    none_neutral_just_curious: 0.7669
    fear_shame_stigma: 0.0648
    anxiety_overwhelm: 0.0880
    positive_health_seeking: 0.0804
    confused: 0.0001   # set weight > 0 to include in random sampling

  barrier:
    knowledge_barrier: 0.6661
    practical_barrier: 0.0165
    social_norms_external_barrier: 0.1045
    social_support_barrier: 0.1075
    internal_struggle_barrier: 0.1054
